#!/usr/bin/env python3
"""
Schema dumper — writes a Python file defining `SCHEMA = {table: [cols]}` for
the `public` schema of a Supabase project. The output is consumed by
scripts/schema-drift-audit.py.

Supports two backends:

1. **Supabase Management API** (preferred for CI — no Postgres password needed)
     SUPABASE_ACCESS_TOKEN=sbp_...
     SUPABASE_PROJECT_REF=gdwpkojugtggozyofpmw
     python3 scripts/dump-schema.py [out_path]

2. **Direct Postgres** (fallback for local dev if you already have the DB URL)
     SUPABASE_DB_URL=postgresql://postgres.[ref]:[pw]@[host]:6543/postgres
     python3 scripts/dump-schema.py [out_path]

Default out_path is /tmp/schema.py, which is what schema-drift-audit.py reads
when no explicit SCHEMA_PATH is set.

The Management API path is preferred because it lets CI run with a single
workspace token secret and never needs the Postgres password — which also
means the password never needs to be rotated just because CI touched it.
"""
import json
import os
import pprint
import sys
import urllib.error
import urllib.request

SCHEMA_SQL = (
    "SELECT table_name, column_name "
    "FROM information_schema.columns "
    "WHERE table_schema = 'public' "
    "ORDER BY table_name, ordinal_position"
)


def dump_via_management_api(token: str, project_ref: str) -> list[tuple[str, str]]:
    """POST the introspection SQL to the Supabase Management API.

    The /database/query endpoint requires a PAT (sbp_...) and returns a JSON
    array of row objects. We re-shape into (table_name, column_name) tuples
    to match the psycopg2 cursor path.
    """
    url = f"https://api.supabase.com/v1/projects/{project_ref}/database/query"
    body = json.dumps({"query": SCHEMA_SQL}).encode()
    req = urllib.request.Request(
        url,
        data=body,
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
            # Supabase rejects requests without a User-Agent with a 403.
            "User-Agent": "schema-drift-audit/1.0",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            data = json.loads(resp.read())
    except urllib.error.HTTPError as e:
        sys.stderr.write(
            f"Management API error {e.code}: {e.read().decode(errors='replace')}\n"
        )
        sys.exit(2)
    if not isinstance(data, list):
        sys.stderr.write(f"Unexpected Management API response shape: {type(data)}\n")
        sys.exit(2)
    return [(row["table_name"], row["column_name"]) for row in data]


def dump_via_psycopg2(db_url: str) -> list[tuple[str, str]]:
    try:
        import psycopg2  # type: ignore
    except ImportError:
        sys.stderr.write(
            "psycopg2 not installed and no SUPABASE_ACCESS_TOKEN set.\n"
            "Either install psycopg2-binary or set SUPABASE_ACCESS_TOKEN + "
            "SUPABASE_PROJECT_REF to use the Management API.\n"
        )
        sys.exit(2)
    conn = psycopg2.connect(db_url)
    try:
        with conn.cursor() as cur:
            cur.execute(SCHEMA_SQL)
            return list(cur.fetchall())
    finally:
        conn.close()


def main() -> int:
    out_path = sys.argv[1] if len(sys.argv) > 1 else "/tmp/schema.py"

    token = os.environ.get("SUPABASE_ACCESS_TOKEN")
    project_ref = os.environ.get("SUPABASE_PROJECT_REF")
    db_url = os.environ.get("SUPABASE_DB_URL") or os.environ.get("DATABASE_URL")

    if token and project_ref:
        source = "management-api"
        rows = dump_via_management_api(token, project_ref)
    elif db_url:
        source = "psycopg2"
        rows = dump_via_psycopg2(db_url)
    else:
        sys.stderr.write(
            "Neither SUPABASE_ACCESS_TOKEN+SUPABASE_PROJECT_REF nor "
            "SUPABASE_DB_URL is set. One of them is required.\n"
        )
        return 2

    schema: dict[str, list[str]] = {}
    for table, col in rows:
        schema.setdefault(table, []).append(col)

    if not schema:
        sys.stderr.write("No tables found in public schema — aborting.\n")
        return 2

    with open(out_path, "w") as f:
        f.write("# Auto-generated by scripts/dump-schema.py — do not edit by hand.\n")
        f.write(f"# Source: {source}\n")
        f.write("# Maps public-schema table/view name to ordered column list.\n")
        f.write("SCHEMA = ")
        f.write(pprint.pformat(schema, width=100, sort_dicts=True))
        f.write("\n")

    print(f"Wrote {len(schema)} tables/views → {out_path} (source: {source})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
