
-- Create verticals reference table
CREATE TABLE public.verticals (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  tier INTEGER NOT NULL,
  default_titles TEXT[] NOT NULL,
  expansion_titles TEXT[],
  trap_titles TEXT[],
  trap_explanations JSONB,
  default_employee_range TEXT[] DEFAULT ARRAY['1-10', '11-20', '21-50'],
  primary_compliance TEXT,
  fear_trigger TEXT,
  scan_detectors TEXT[],
  default_pain_points TEXT[],
  icon TEXT,
  description TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS: readable by authenticated users only
ALTER TABLE public.verticals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can read verticals" ON public.verticals
  FOR SELECT USING (auth.role() = 'authenticated');

-- Seed verticals
INSERT INTO public.verticals (name, tier, default_titles, expansion_titles, trap_titles, trap_explanations, default_employee_range, primary_compliance, fear_trigger, scan_detectors, default_pain_points, icon, description, sort_order) VALUES

('Law Firms', 1, 
  ARRAY['attorney', 'lawyer'], 
  ARRAY['managing partner', 'legal administrator'], 
  ARRAY['partner', 'paralegal', 'JD', 'Esq'],
  '{"partner": "Pulls partners from consulting, accounting, VC — all mixed together", "paralegal": "Not a decision maker for security purchases", "JD": "Academic credential, not a job title. Near-zero results", "Esq": "Honorific suffix, not a job title in Apollo"}'::jsonb,
  ARRAY['1-10', '11-20', '21-50'],
  'ABA Ethics Rules, FL Bar',
  'Wire fraud via spoofed email costs avg $150K. Your DMARC is not configured.',
  ARRAY['DMARC/SPF', 'SSL', 'Security Headers'],
  ARRAY['Wire fraud / BEC attacks', 'Client confidentiality breach', 'Bar compliance requirements', 'Email domain spoofing'],
  '⚖️', 'Law firms, attorneys, legal practices', 1),

('Real Estate / Title Companies', 1, 
  ARRAY['real estate broker', 'title agent'], 
  ARRAY['escrow officer', 'real estate agent'], 
  ARRAY['realtor', 'broker', 'agent'],
  '{"realtor": "Too broad — everyone with a real estate license", "broker": "Without qualifier pulls mortgage, insurance, stock brokers", "agent": "Without qualifier pulls insurance agents, talent agents, etc."}'::jsonb,
  ARRAY['1-10', '11-20', '21-50'],
  'CFPB, ALTA Best Practices',
  'A title company in FL lost $1.2M from a single spoofed wire instruction email.',
  ARRAY['DMARC/SPF', 'SSL', 'Security Headers'],
  ARRAY['Wire fraud on closings', 'Email spoofing of agents/escrow', 'Client PII exposure', 'ALTA Best Practices compliance'],
  '🏠', 'Real estate brokerages, title & escrow companies', 2),

('Medical Practices', 1, 
  ARRAY['physician', 'medical director'], 
  ARRAY['chiropractor', 'optometrist', 'practice administrator'], 
  ARRAY['doctor', 'practice owner', 'healthcare administrator', 'MD', 'DO'],
  '{"doctor": "Too broad — pulls PhDs, academics, non-clinical", "practice owner": "OR logic pulls owners from every industry", "healthcare administrator": "Pulls hospital admin, insurance, large health systems", "MD": "Credential, not title. Near-zero results", "DO": "Credential, not title. Near-zero results"}'::jsonb,
  ARRAY['1-10', '11-20', '21-50'],
  'HIPAA, HITECH Act',
  'HIPAA fines start at $100/violation. Your patient portal has no HSTS header.',
  ARRAY['DMARC/SPF', 'SSL', 'HSTS', 'CSP'],
  ARRAY['HIPAA violation fines', 'Patient portal vulnerabilities', 'Ransomware downtime', 'Staff phishing susceptibility'],
  '🏥', 'Medical practices, clinics, specialty care', 3),

('Dental Practices', 1, 
  ARRAY['dentist'], 
  ARRAY['dental office manager', 'orthodontist', 'endodontist', 'periodontist'], 
  ARRAY['practice owner', 'office manager', 'DDS', 'DMD'],
  '{"practice owner": "OR logic pulls owners from ALL industries — vet, medical, PT, etc.", "office manager": "Too generic — matches every small business", "DDS": "Academic credential, not a job title. Near-zero results", "DMD": "Academic credential, not a job title. Near-zero results"}'::jsonb,
  ARRAY['1-10', '11-20', '21-50'],
  'HIPAA',
  'Same HIPAA rules as hospitals apply to your 5-person practice.',
  ARRAY['DMARC/SPF', 'SSL', 'HSTS'],
  ARRAY['HIPAA compliance gaps', 'Patient data breach risk', 'Phishing targeting staff', 'No cybersecurity budget or expertise'],
  '🦷', 'Dental offices, orthodontics, oral surgery', 4),

('Financial Advisors', 1, 
  ARRAY['financial advisor', 'wealth manager'], 
  ARRAY['financial planner', 'investment advisor'], 
  ARRAY['advisor', 'analyst', 'broker'],
  '{"advisor": "Too broad — pulls HR advisors, business advisors, education advisors", "analyst": "Pulls corporate financial analysts, not firm owners", "broker": "Without qualifier pulls insurance, real estate, stock brokers"}'::jsonb,
  ARRAY['1-10', '11-20', '21-50'],
  'SEC Reg S-P, FINRA',
  'SEC is now auditing cybersecurity programs. Your website has missing security headers.',
  ARRAY['DMARC/SPF', 'SSL', 'Security Headers', 'CSP'],
  ARRAY['SEC/FINRA cybersecurity audits', 'Client financial data exposure', 'Credential theft', 'Regulatory compliance gaps'],
  '💰', 'Financial advisory firms, wealth management', 5),

('Insurance Agencies', 2, 
  ARRAY['insurance agent', 'insurance broker'], 
  ARRAY['agency principal'], 
  ARRAY['agent', 'underwriter'],
  '{"agent": "Without insurance qualifier pulls real estate, talent, travel agents", "underwriter": "Usually works at carrier level, not agency"}'::jsonb,
  ARRAY['1-10', '11-20', '21-50'],
  'GLBA, FL Dept of Insurance',
  'FL insurance data protection rules tightened in 2024. Your DMARC record is set to none.',
  ARRAY['DMARC/SPF', 'SSL', 'Security Headers'],
  ARRAY['GLBA compliance', 'Client PII and health data', 'Agency management system breach', 'FL insurance regulation changes'],
  '🛡️', 'Insurance agencies, brokerages', 6),

('Accounting / CPA Firms', 2, 
  ARRAY['CPA', 'accountant'], 
  ARRAY['tax preparer', 'bookkeeper'], 
  ARRAY['partner', 'financial advisor', 'controller', 'EA'],
  '{"partner": "Pulls partners from every industry", "financial advisor": "Different vertical — wealth management, not accounting", "controller": "Usually in-house at companies, not at CPA firms", "EA": "Enrolled Agent — almost nobody uses this as title"}'::jsonb,
  ARRAY['1-10', '11-20', '21-50'],
  'IRS WISP requirement',
  'IRS requires a Written Information Security Plan. Tax season is peak phishing target.',
  ARRAY['DMARC/SPF', 'SSL', 'Security Headers'],
  ARRAY['IRS WISP requirement', 'Tax season phishing surge', 'Client financial data theft', 'Ransomware during filing season'],
  '📊', 'CPA firms, tax preparers, bookkeeping', 7),

('Auto Dealerships', 2, 
  ARRAY['dealer principal', 'general manager'], 
  NULL, 
  ARRAY['sales manager', 'owner'],
  '{"sales manager": "Every retail company has sales managers — massive pollution", "owner": "Every business owner in every industry"}'::jsonb,
  ARRAY['11-20', '21-50', '51-100', '101-200'],
  'FTC Safeguards Rule',
  'FTC Safeguards Rule is now enforced. The CDK Global hack shut down 15,000 dealerships.',
  ARRAY['DMARC/SPF', 'SSL', 'Security Headers'],
  ARRAY['FTC Safeguards Rule compliance', 'Credit application data exposure', 'CDK-style supply chain attack', 'Customer PII breach'],
  '🚗', 'Auto dealerships, car dealers', 8),

('Hotels / Hospitality', 2, 
  ARRAY['hotel manager', 'hotel general manager'], 
  ARRAY['hotel owner', 'director of operations'], 
  ARRAY['general manager', 'hospitality', 'manager'],
  '{"general manager": "Without hotel qualifier pulls every restaurant, retail, venue", "hospitality": "Too vague — pulls event planners, caterers, tourism", "manager": "Most generic title in existence"}'::jsonb,
  ARRAY['1-10', '11-20', '21-50', '51-100', '101-200'],
  'PCI-DSS',
  'Your hotel processes thousands of credit cards monthly. One breach means a class action.',
  ARRAY['DMARC/SPF', 'SSL', 'PCI indicators'],
  ARRAY['PCI-DSS credit card compliance', 'Guest data breach', 'Wi-Fi network vulnerabilities', 'Reservation system attacks'],
  '🏨', 'Hotels, resorts, boutique hospitality', 9),

('Property Management', 2, 
  ARRAY['property manager', 'community manager'], 
  ARRAY['regional manager'], 
  ARRAY['manager', 'leasing'],
  '{"manager": "Every company has managers — millions of results", "leasing": "Pulls junior leasing agents, not decision makers"}'::jsonb,
  ARRAY['1-10', '11-20', '21-50'],
  'FL Tenant Data Laws',
  'Tenant SSNs, bank accounts, lease documents — all stored on your systems.',
  ARRAY['DMARC/SPF', 'SSL', 'Security Headers'],
  ARRAY['Tenant PII exposure', 'Payment processing security', 'Maintenance portal vulnerabilities', 'Wire fraud on rent payments'],
  '🏢', 'Property management, HOAs, condos', 10),

('Construction / General Contractors', 2, 
  ARRAY['general contractor', 'construction manager'], 
  ARRAY['project manager'], 
  ARRAY['contractor', 'project manager', 'owner'],
  '{"contractor": "Too broad — IT contractors, staffing contractors, etc.", "project manager": "Without construction context pulls every PM in tech", "owner": "Every business owner"}'::jsonb,
  ARRAY['1-10', '11-20', '21-50', '51-100', '101-200'],
  'None specific',
  'Construction wire fraud averages $250K per incident. Your email domain is spoofable.',
  ARRAY['DMARC/SPF', 'SSL'],
  ARRAY['Invoice wire fraud ($250K avg)', 'Email domain spoofing', 'Subcontractor payment interception', 'Blueprint/bid data theft'],
  '🏗️', 'General contractors, construction companies', 11),

('MSPs / IT Services', 2, 
  ARRAY['IT director', 'managed services'], 
  ARRAY['vCIO', 'network administrator'], 
  ARRAY['IT manager', 'technology consultant', 'owner', 'help desk', 'technician'],
  '{"IT manager": "Pulls internal IT staff at every company, not MSP owners", "technology consultant": "Extremely broad — management consultants, freelancers", "owner": "Every business owner", "help desk": "Not decision maker, too junior", "technician": "Not decision maker, too junior"}'::jsonb,
  ARRAY['1-10', '11-20', '21-50', '51-100', '101-200'],
  'Supply chain liability',
  'If your MSP gets hacked, ALL your clients get hacked. Supply chain attacks are the #1 MSP threat.',
  ARRAY['DMARC/SPF', 'SSL', 'Security Headers', 'CSP'],
  ARRAY['Supply chain attack liability', 'Client data breach cascade', 'RMM tool compromise', 'Cyber insurance requirements'],
  '💻', 'Managed Service Providers, IT services', 12),

('Home Health / Senior Care', 3, 
  ARRAY['home health administrator'], 
  ARRAY['director of nursing'], 
  ARRAY['caregiver', 'nurse'],
  '{"caregiver": "Frontline staff, not a decision maker", "nurse": "Too broad — pulls hospital nurses, clinics, schools"}'::jsonb,
  ARRAY['1-10', '11-20', '21-50'],
  'HIPAA',
  'Home health agencies are the #1 HIPAA audit target in 2025.',
  ARRAY['DMARC/SPF', 'SSL', 'HSTS'],
  ARRAY['HIPAA audit (top target)', 'Patient data on mobile devices', 'Caregiver account compromise', 'Telehealth security gaps'],
  '🏡', 'Home health agencies, senior care', 13),

('Veterinary Clinics', 3, 
  ARRAY['veterinarian'], 
  ARRAY['veterinary practice manager'], 
  ARRAY['vet'],
  '{"vet": "Can pull veteran-related titles. Always use full word veterinarian"}'::jsonb,
  ARRAY['1-10', '11-20'],
  'Payment data + client PII',
  'Payment data and client PII at risk. Growing cybersecurity awareness in the vet industry.',
  ARRAY['DMARC/SPF', 'SSL', 'Security Headers'],
  ARRAY['Client payment data risk', 'Practice management system breach', 'Staff phishing', 'No dedicated IT security'],
  '🐾', 'Veterinary clinics, animal hospitals', 14),

('Web / Marketing Agencies', 3, 
  ARRAY['agency owner', 'creative director'], 
  ARRAY['digital marketing', 'SEO'], 
  ARRAY['marketing manager', 'founder', 'owner', 'web designer', 'graphic designer'],
  '{"marketing manager": "Pulls in-house marketers at every company", "founder": "Every startup founder", "owner": "Every business owner", "web designer": "Usually freelancer or junior, not decision maker", "graphic designer": "Not decision maker for security purchases"}'::jsonb,
  ARRAY['1-10', '11-20', '21-50'],
  'Low regulatory pressure',
  'Perfect ScanToSell demo target. Best as partnership/reseller play, not direct cyber buyer.',
  ARRAY['DMARC/SPF', 'SSL', 'Security Headers', 'Performance'],
  ARRAY['Client website defacement', 'CMS/hosting credential theft', 'Data breach of client assets', 'Reputation risk from compromise'],
  '🎨', 'Web agencies, digital marketing, creative studios', 15);

-- Add vertical reference columns to campaign_profiles
ALTER TABLE public.campaign_profiles ADD COLUMN IF NOT EXISTS vertical_id UUID REFERENCES public.verticals(id);
ALTER TABLE public.campaign_profiles ADD COLUMN IF NOT EXISTS custom_vertical BOOLEAN DEFAULT FALSE;
